// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file nibiru/devgas/v1/query.proto (package nibiru.devgas.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { FeeShare } from "./devgas_pb.js";
import { ModuleParams } from "./genesis_pb.js";

/**
 * QueryFeeSharesRequest is the request type for the Query/FeeShares RPC method.
 *
 * @generated from message nibiru.devgas.v1.QueryFeeSharesRequest
 */
export class QueryFeeSharesRequest extends Message<QueryFeeSharesRequest> {
  /**
   * TODO feat(devgas): re-implement the paginated version
   * TODO feat(colletions): add automatic pagination generation
   *
   * pagination defines an optional pagination for the request.
   * cosmos.base.query.v1beta1.PageRequest pagination = 1;
   *
   * @generated from field: string deployer = 1;
   */
  deployer = "";

  constructor(data?: PartialMessage<QueryFeeSharesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.devgas.v1.QueryFeeSharesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deployer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryFeeSharesRequest {
    return new QueryFeeSharesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryFeeSharesRequest {
    return new QueryFeeSharesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryFeeSharesRequest {
    return new QueryFeeSharesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryFeeSharesRequest | PlainMessage<QueryFeeSharesRequest> | undefined, b: QueryFeeSharesRequest | PlainMessage<QueryFeeSharesRequest> | undefined): boolean {
    return proto3.util.equals(QueryFeeSharesRequest, a, b);
  }
}

/**
 * QueryFeeSharesResponse is the response type for the Query/FeeShares RPC
 * method.
 *
 * @generated from message nibiru.devgas.v1.QueryFeeSharesResponse
 */
export class QueryFeeSharesResponse extends Message<QueryFeeSharesResponse> {
  /**
   * FeeShare is the slice of all stored Reveneue for the deployer
   *
   * @generated from field: repeated nibiru.devgas.v1.FeeShare feeshare = 1;
   */
  feeshare: FeeShare[] = [];

  constructor(data?: PartialMessage<QueryFeeSharesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.devgas.v1.QueryFeeSharesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "feeshare", kind: "message", T: FeeShare, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryFeeSharesResponse {
    return new QueryFeeSharesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryFeeSharesResponse {
    return new QueryFeeSharesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryFeeSharesResponse {
    return new QueryFeeSharesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryFeeSharesResponse | PlainMessage<QueryFeeSharesResponse> | undefined, b: QueryFeeSharesResponse | PlainMessage<QueryFeeSharesResponse> | undefined): boolean {
    return proto3.util.equals(QueryFeeSharesResponse, a, b);
  }
}

/**
 * QueryFeeShareRequest is the request type for the Query/FeeShare RPC method.
 *
 * @generated from message nibiru.devgas.v1.QueryFeeShareRequest
 */
export class QueryFeeShareRequest extends Message<QueryFeeShareRequest> {
  /**
   * contract_address of a registered contract in bech32 format
   *
   * @generated from field: string contract_address = 1;
   */
  contractAddress = "";

  constructor(data?: PartialMessage<QueryFeeShareRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.devgas.v1.QueryFeeShareRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryFeeShareRequest {
    return new QueryFeeShareRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryFeeShareRequest {
    return new QueryFeeShareRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryFeeShareRequest {
    return new QueryFeeShareRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryFeeShareRequest | PlainMessage<QueryFeeShareRequest> | undefined, b: QueryFeeShareRequest | PlainMessage<QueryFeeShareRequest> | undefined): boolean {
    return proto3.util.equals(QueryFeeShareRequest, a, b);
  }
}

/**
 * QueryFeeShareResponse is the response type for the Query/FeeShare RPC method.
 *
 * @generated from message nibiru.devgas.v1.QueryFeeShareResponse
 */
export class QueryFeeShareResponse extends Message<QueryFeeShareResponse> {
  /**
   * FeeShare is a stored Reveneue for the queried contract
   *
   * @generated from field: nibiru.devgas.v1.FeeShare feeshare = 1;
   */
  feeshare?: FeeShare;

  constructor(data?: PartialMessage<QueryFeeShareResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.devgas.v1.QueryFeeShareResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "feeshare", kind: "message", T: FeeShare },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryFeeShareResponse {
    return new QueryFeeShareResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryFeeShareResponse {
    return new QueryFeeShareResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryFeeShareResponse {
    return new QueryFeeShareResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryFeeShareResponse | PlainMessage<QueryFeeShareResponse> | undefined, b: QueryFeeShareResponse | PlainMessage<QueryFeeShareResponse> | undefined): boolean {
    return proto3.util.equals(QueryFeeShareResponse, a, b);
  }
}

/**
 * QueryParamsRequest is the request type for the Query/Params RPC method.
 *
 * @generated from message nibiru.devgas.v1.QueryParamsRequest
 */
export class QueryParamsRequest extends Message<QueryParamsRequest> {
  constructor(data?: PartialMessage<QueryParamsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.devgas.v1.QueryParamsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined, b: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined): boolean {
    return proto3.util.equals(QueryParamsRequest, a, b);
  }
}

/**
 * QueryParamsResponse is the response type for the Query/Params RPC method.
 *
 * @generated from message nibiru.devgas.v1.QueryParamsResponse
 */
export class QueryParamsResponse extends Message<QueryParamsResponse> {
  /**
   * params is the returned FeeShare parameter
   *
   * @generated from field: nibiru.devgas.v1.ModuleParams params = 1;
   */
  params?: ModuleParams;

  constructor(data?: PartialMessage<QueryParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.devgas.v1.QueryParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: ModuleParams },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined, b: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined): boolean {
    return proto3.util.equals(QueryParamsResponse, a, b);
  }
}

/**
 * QueryFeeSharesByWithdrawerRequest is the request type for the
 * Query/FeeSharesByWithdrawer RPC method.
 *
 * @generated from message nibiru.devgas.v1.QueryFeeSharesByWithdrawerRequest
 */
export class QueryFeeSharesByWithdrawerRequest extends Message<QueryFeeSharesByWithdrawerRequest> {
  /**
   * withdrawer_address in bech32 format
   *
   * @generated from field: string withdrawer_address = 1;
   */
  withdrawerAddress = "";

  constructor(data?: PartialMessage<QueryFeeSharesByWithdrawerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.devgas.v1.QueryFeeSharesByWithdrawerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "withdrawer_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryFeeSharesByWithdrawerRequest {
    return new QueryFeeSharesByWithdrawerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryFeeSharesByWithdrawerRequest {
    return new QueryFeeSharesByWithdrawerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryFeeSharesByWithdrawerRequest {
    return new QueryFeeSharesByWithdrawerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryFeeSharesByWithdrawerRequest | PlainMessage<QueryFeeSharesByWithdrawerRequest> | undefined, b: QueryFeeSharesByWithdrawerRequest | PlainMessage<QueryFeeSharesByWithdrawerRequest> | undefined): boolean {
    return proto3.util.equals(QueryFeeSharesByWithdrawerRequest, a, b);
  }
}

/**
 * QueryFeeSharesByWithdrawerResponse is the response type for the
 * Query/FeeSharesByWithdrawer RPC method.
 *
 * @generated from message nibiru.devgas.v1.QueryFeeSharesByWithdrawerResponse
 */
export class QueryFeeSharesByWithdrawerResponse extends Message<QueryFeeSharesByWithdrawerResponse> {
  /**
   * @generated from field: repeated nibiru.devgas.v1.FeeShare feeshare = 1;
   */
  feeshare: FeeShare[] = [];

  constructor(data?: PartialMessage<QueryFeeSharesByWithdrawerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.devgas.v1.QueryFeeSharesByWithdrawerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "feeshare", kind: "message", T: FeeShare, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryFeeSharesByWithdrawerResponse {
    return new QueryFeeSharesByWithdrawerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryFeeSharesByWithdrawerResponse {
    return new QueryFeeSharesByWithdrawerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryFeeSharesByWithdrawerResponse {
    return new QueryFeeSharesByWithdrawerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryFeeSharesByWithdrawerResponse | PlainMessage<QueryFeeSharesByWithdrawerResponse> | undefined, b: QueryFeeSharesByWithdrawerResponse | PlainMessage<QueryFeeSharesByWithdrawerResponse> | undefined): boolean {
    return proto3.util.equals(QueryFeeSharesByWithdrawerResponse, a, b);
  }
}

