// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file sunrise/da/v1/params.proto (package sunrise.da.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Coin } from "../../../cosmos/base/v1beta1/coin_pb.js";

/**
 * Params defines the parameters for the module.
 *
 * @generated from message sunrise.da.v1.Params
 */
export class Params extends Message<Params> {
  /**
   * @generated from field: uint64 publish_data_gas = 1;
   */
  publishDataGas = protoInt64.zero;

  /**
   * Invalid shard threshold required to go to STATUS_CHALLENGING.
   *
   * @generated from field: string challenge_threshold = 2;
   */
  challengeThreshold = "";

  /**
   * https://docs.sunriselayer.io/learn/sunrise/data-availability#the-condition-of-data-availability
   *
   * @generated from field: string replication_factor = 3;
   */
  replicationFactor = "";

  /**
   * How many blocks of slash are done every
   *
   * @generated from field: uint64 slash_epoch = 4;
   */
  slashEpoch = protoInt64.zero;

  /**
   * (number of challenges a validator did not submit proof / number of all challenge) is over this threshold in an epoch
   * that validator will be slashed
   *
   * @generated from field: string slash_fault_threshold = 5;
   */
  slashFaultThreshold = "";

  /**
   * voting power deducted during slash
   *
   * @generated from field: string slash_fraction = 6;
   */
  slashFraction = "";

  /**
   * @generated from field: google.protobuf.Duration challenge_period = 7;
   */
  challengePeriod?: Duration;

  /**
   * @generated from field: google.protobuf.Duration proof_period = 8;
   */
  proofPeriod?: Duration;

  /**
   * @generated from field: google.protobuf.Duration rejected_removal_period = 9;
   */
  rejectedRemovalPeriod?: Duration;

  /**
   * @generated from field: google.protobuf.Duration verified_removal_period = 10;
   */
  verifiedRemovalPeriod?: Duration;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin publish_data_collateral = 11;
   */
  publishDataCollateral: Coin[] = [];

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin submit_invalidity_collateral = 12;
   */
  submitInvalidityCollateral: Coin[] = [];

  /**
   * @generated from field: bytes zkp_verifying_key = 13;
   */
  zkpVerifyingKey = new Uint8Array(0);

  /**
   * proving key used in sunrise-data
   *
   * @generated from field: bytes zkp_proving_key = 14;
   */
  zkpProvingKey = new Uint8Array(0);

  /**
   * min_shard_count used in sunrise-data
   *
   * @generated from field: uint64 min_shard_count = 15;
   */
  minShardCount = protoInt64.zero;

  /**
   * max_shard_count used in sunrise-data
   *
   * @generated from field: uint64 max_shard_count = 16;
   */
  maxShardCount = protoInt64.zero;

  /**
   * max_shard_size used in sunrise-data
   *
   * @generated from field: uint64 max_shard_size = 17;
   */
  maxShardSize = protoInt64.zero;

  constructor(data?: PartialMessage<Params>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sunrise.da.v1.Params";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "publish_data_gas", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "challenge_threshold", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "replication_factor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "slash_epoch", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "slash_fault_threshold", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "slash_fraction", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "challenge_period", kind: "message", T: Duration },
    { no: 8, name: "proof_period", kind: "message", T: Duration },
    { no: 9, name: "rejected_removal_period", kind: "message", T: Duration },
    { no: 10, name: "verified_removal_period", kind: "message", T: Duration },
    { no: 11, name: "publish_data_collateral", kind: "message", T: Coin, repeated: true },
    { no: 12, name: "submit_invalidity_collateral", kind: "message", T: Coin, repeated: true },
    { no: 13, name: "zkp_verifying_key", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 14, name: "zkp_proving_key", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 15, name: "min_shard_count", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 16, name: "max_shard_count", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 17, name: "max_shard_size", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params {
    return new Params().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJsonString(jsonString, options);
  }

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean {
    return proto3.util.equals(Params, a, b);
  }
}

