// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file nibiru/tokenfactory/v1/state.proto (package nibiru.tokenfactory.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * DenomAuthorityMetadata specifies metadata foraddresses that have specific
 * capabilities over a token factory denom. Right now there is only one Admin
 * permission, but is planned to be extended to the future.
 *
 * @generated from message nibiru.tokenfactory.v1.DenomAuthorityMetadata
 */
export class DenomAuthorityMetadata extends Message<DenomAuthorityMetadata> {
  /**
   * Admin: Bech32 address of the admin for the tokefactory denom. Can be empty
   * for no admin.
   *
   * @generated from field: string admin = 1;
   */
  admin = "";

  constructor(data?: PartialMessage<DenomAuthorityMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.tokenfactory.v1.DenomAuthorityMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "admin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DenomAuthorityMetadata {
    return new DenomAuthorityMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DenomAuthorityMetadata {
    return new DenomAuthorityMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DenomAuthorityMetadata {
    return new DenomAuthorityMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: DenomAuthorityMetadata | PlainMessage<DenomAuthorityMetadata> | undefined, b: DenomAuthorityMetadata | PlainMessage<DenomAuthorityMetadata> | undefined): boolean {
    return proto3.util.equals(DenomAuthorityMetadata, a, b);
  }
}

/**
 * ModuleParams defines the parameters for the tokenfactory module.
 *
 * ### On Denom Creation Costs
 *
 * We'd like for fees to be paid by the user/signer of a ransaction, but in many
 * casess, token creation is abstracted away behind a smart contract. Setting a
 * nonzero `denom_creation_fee` would force each contract to handle collecting
 * and paying a fees for denom (factory/{contract-addr}/{subdenom}) creation on
 * behalf of the end user.
 *
 * For IBC token transfers, it's unclear who should pay the fee—the contract,
 * the relayer, or the original sender?
 * > "Charging fees will mess up composability, the same way Terra transfer tax
 *   caused all kinds of headaches for contract devs." - @ethanfrey
 *
 * ### Recommended Solution
 *
 * Have the end user (signer) pay fees directly in the form of higher gas costs.
 * This way, contracts won't need to handle collecting or paying fees. And for
 * IBC, the gas costs are already paid by the original sender and can be
 * estimated by the relayer. It's easier to tune gas costs to make spam
 * prohibitively expensive since there are per-transaction and per-block gas
 * limits.
 *
 * See https://github.com/CosmWasm/token-factory/issues/11 for the initial
 * discussion of the issue with @ethanfrey and @valardragon.
 *
 * @generated from message nibiru.tokenfactory.v1.ModuleParams
 */
export class ModuleParams extends Message<ModuleParams> {
  /**
   * Adds gas consumption to the execution of `MsgCreateDenom` as a method of
   * spam prevention. Defaults to 10 NIBI.
   *
   * @generated from field: uint64 denom_creation_gas_consume = 1;
   */
  denomCreationGasConsume = protoInt64.zero;

  constructor(data?: PartialMessage<ModuleParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.tokenfactory.v1.ModuleParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "denom_creation_gas_consume", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModuleParams {
    return new ModuleParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModuleParams {
    return new ModuleParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModuleParams {
    return new ModuleParams().fromJsonString(jsonString, options);
  }

  static equals(a: ModuleParams | PlainMessage<ModuleParams> | undefined, b: ModuleParams | PlainMessage<ModuleParams> | undefined): boolean {
    return proto3.util.equals(ModuleParams, a, b);
  }
}

/**
 * TFDenom is a token factory (TF) denom. The canonical representation is
 * "tf/{creator}/{subdenom}", its unique denomination in the x/bank module.
 *
 * @generated from message nibiru.tokenfactory.v1.TFDenom
 */
export class TFDenom extends Message<TFDenom> {
  /**
   * Creator: Bech32 address of the creator of the denom.
   *
   * @generated from field: string creator = 1;
   */
  creator = "";

  /**
   * Subdenom: Unique suffix of a token factory denom. A subdenom is specific
   * to a given creator. It is the name given during a token factory "Mint".
   *
   * @generated from field: string subdenom = 2;
   */
  subdenom = "";

  constructor(data?: PartialMessage<TFDenom>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.tokenfactory.v1.TFDenom";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subdenom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TFDenom {
    return new TFDenom().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TFDenom {
    return new TFDenom().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TFDenom {
    return new TFDenom().fromJsonString(jsonString, options);
  }

  static equals(a: TFDenom | PlainMessage<TFDenom> | undefined, b: TFDenom | PlainMessage<TFDenom> | undefined): boolean {
    return proto3.util.equals(TFDenom, a, b);
  }
}

/**
 * GenesisState for the Token Factory module.
 *
 * @generated from message nibiru.tokenfactory.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * @generated from field: nibiru.tokenfactory.v1.ModuleParams params = 1;
   */
  params?: ModuleParams;

  /**
   * @generated from field: repeated nibiru.tokenfactory.v1.GenesisDenom factory_denoms = 2;
   */
  factoryDenoms: GenesisDenom[] = [];

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.tokenfactory.v1.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: ModuleParams },
    { no: 2, name: "factory_denoms", kind: "message", T: GenesisDenom, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

/**
 * GenesisDenom defines a tokenfactory denoms in the genesis state.
 *
 * @generated from message nibiru.tokenfactory.v1.GenesisDenom
 */
export class GenesisDenom extends Message<GenesisDenom> {
  /**
   * @generated from field: string denom = 1;
   */
  denom = "";

  /**
   * @generated from field: nibiru.tokenfactory.v1.DenomAuthorityMetadata authority_metadata = 2;
   */
  authorityMetadata?: DenomAuthorityMetadata;

  constructor(data?: PartialMessage<GenesisDenom>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "nibiru.tokenfactory.v1.GenesisDenom";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "authority_metadata", kind: "message", T: DenomAuthorityMetadata },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisDenom {
    return new GenesisDenom().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisDenom {
    return new GenesisDenom().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisDenom {
    return new GenesisDenom().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisDenom | PlainMessage<GenesisDenom> | undefined, b: GenesisDenom | PlainMessage<GenesisDenom> | undefined): boolean {
    return proto3.util.equals(GenesisDenom, a, b);
  }
}

