// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file milkyway/investors/v1/genesis.proto (package milkyway.investors.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * GenesisState defines the investors module's genesis state.
 *
 * @generated from message milkyway.investors.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * InvestorsRewardRatio defines the proportion of staking rewards allocated to
   * vesting investors relative to normal users. For example, if the ratio is 0.3,
   * then the investors would receive 30% of the staking rewards. The rest of the
   * rewards would be sent to the community pool.
   *
   * @generated from field: string investors_reward_ratio = 1;
   */
  investorsRewardRatio = "";

  /**
   * VestingInvestorsAddresses defines the list of investor addresses that are
   * still in their vesting period and will receive rewards based on the
   * InvestorsRewardRatio.
   *
   * @generated from field: repeated string vesting_investors_addresses = 2;
   */
  vestingInvestorsAddresses: string[] = [];

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "milkyway.investors.v1.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "investors_reward_ratio", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "vesting_investors_addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

