// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file milkyway/investors/v1/query.proto (package milkyway.investors.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryInvestorsRewardRatioRequest, QueryInvestorsRewardRatioResponse, QueryVestingInvestorsRequest, QueryVestingInvestorsResponse } from "./query_pb.js";

const TYPE_NAME = "milkyway.investors.v1.Query";

/**
 * InvestorsRewardRatio queries the investors reward ratio.
 *
 * @generated from rpc milkyway.investors.v1.Query.InvestorsRewardRatio
 */
export const QueryInvestorsRewardRatioService = {
  typeName: TYPE_NAME,
  method: "InvestorsRewardRatio",
  Request: QueryInvestorsRewardRatioRequest,
  Response: QueryInvestorsRewardRatioResponse,
} as const;

/**
 * VestingInvestors queries the list of vesting investors.
 *
 * @generated from rpc milkyway.investors.v1.Query.VestingInvestors
 */
export const QueryVestingInvestorsService = {
  typeName: TYPE_NAME,
  method: "VestingInvestors",
  Request: QueryVestingInvestorsRequest,
  Response: QueryVestingInvestorsResponse,
} as const;

