// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file atomone/photon/v1/photon.proto (package atomone.photon.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Params defines the parameters for the x/photon module.
 *
 * @generated from message atomone.photon.v1.Params
 */
export class Params extends Message<Params> {
  /**
   * Allow to mint photon or not
   *
   * @generated from field: bool mint_disabled = 1;
   */
  mintDisabled = false;

  /**
   * tx_fee_exceptions holds the msg type urls that are allowed to use some
   * different tx fee coins than photon.
   * A wildcard "*" can be used to allow all transactions to use any fee denom.
   *
   * @generated from field: repeated string tx_fee_exceptions = 2;
   */
  txFeeExceptions: string[] = [];

  constructor(data?: PartialMessage<Params>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "atomone.photon.v1.Params";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mint_disabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "tx_fee_exceptions", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params {
    return new Params().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJsonString(jsonString, options);
  }

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean {
    return proto3.util.equals(Params, a, b);
  }
}

