// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file coreum/dex/v1/tx.proto (package coreum.dex.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EmptyResponse, MsgCancelOrder, MsgCancelOrdersByDenom, MsgPlaceOrder, MsgUpdateParams } from "./tx_pb.js";

const TYPE_NAME = "coreum.dex.v1.Msg";

/**
 * UpdateParams is a governance operation to modify the parameters of the module.
 * NOTE: all parameters must be provided.
 *
 * @generated from rpc coreum.dex.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: EmptyResponse,
} as const;

/**
 * PlaceOrder place an order on orderbook.
 *
 * @generated from rpc coreum.dex.v1.Msg.PlaceOrder
 */
export const MsgPlaceOrderService = {
  typeName: TYPE_NAME,
  method: "PlaceOrder",
  Request: MsgPlaceOrder,
  Response: EmptyResponse,
} as const;

/**
 * CancelOrder cancels an order in the orderbook.
 *
 * @generated from rpc coreum.dex.v1.Msg.CancelOrder
 */
export const MsgCancelOrderService = {
  typeName: TYPE_NAME,
  method: "CancelOrder",
  Request: MsgCancelOrder,
  Response: EmptyResponse,
} as const;

/**
 * CancelOrdersByDenom cancels all orders by denom and account.
 *
 * @generated from rpc coreum.dex.v1.Msg.CancelOrdersByDenom
 */
export const MsgCancelOrdersByDenomService = {
  typeName: TYPE_NAME,
  method: "CancelOrdersByDenom",
  Request: MsgCancelOrdersByDenom,
  Response: EmptyResponse,
} as const;

