// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file injective/downtimedetector/v1beta1/query.proto (package injective.downtimedetector.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RecoveredSinceDowntimeOfLengthRequest, RecoveredSinceDowntimeOfLengthResponse } from "./query_pb.js";

const TYPE_NAME = "injective.downtimedetector.v1beta1.Query";

/**
 * @generated from rpc injective.downtimedetector.v1beta1.Query.RecoveredSinceDowntimeOfLength
 */
export const QueryRecoveredSinceDowntimeOfLengthService = {
  typeName: TYPE_NAME,
  method: "RecoveredSinceDowntimeOfLength",
  Request: RecoveredSinceDowntimeOfLengthRequest,
  Response: RecoveredSinceDowntimeOfLengthResponse,
} as const;

