// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file elys/masterchef/query.proto (package elys.masterchef, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAllLiquidityPoolTVLRequest, QueryAllLiquidityPoolTVLResponse, QueryAprRequest, QueryAprResponse, QueryAprsRequest, QueryAprsResponse, QueryChainTVLRequest, QueryChainTVLResponse, QueryExternalIncentiveRequest, QueryExternalIncentiveResponse, QueryListFeeInfoRequest, QueryListFeeInfoResponse, QueryListPoolInfosRequest, QueryListPoolInfosResponse, QueryParamsRequest, QueryParamsResponse, QueryPendingRewardsRequest, QueryPendingRewardsResponse, QueryPoolAprsRequest, QueryPoolAprsResponse, QueryPoolInfoRequest, QueryPoolInfoResponse, QueryPoolRewardInfoRequest, QueryPoolRewardInfoResponse, QueryPoolRewardsRequest, QueryPoolRewardsResponse, QueryShowFeeInfoRequest, QueryShowFeeInfoResponse, QueryStableStakeAprRequest, QueryStableStakeAprResponse, QueryTotalPendingRewardsRequest, QueryTotalPendingRewardsResponse, QueryUserPendingRewardRequest, QueryUserPendingRewardResponse, QueryUserRewardInfoRequest, QueryUserRewardInfoResponse } from "./query_pb.js";

const TYPE_NAME = "elys.masterchef.Query";

/**
 * Parameters queries the parameters of the module.
 *
 * @generated from rpc elys.masterchef.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.ExternalIncentive
 */
export const QueryExternalIncentiveService = {
  typeName: TYPE_NAME,
  method: "ExternalIncentive",
  Request: QueryExternalIncentiveRequest,
  Response: QueryExternalIncentiveResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.PoolInfo
 */
export const QueryPoolInfoService = {
  typeName: TYPE_NAME,
  method: "PoolInfo",
  Request: QueryPoolInfoRequest,
  Response: QueryPoolInfoResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.ListPoolInfos
 */
export const QueryListPoolInfosService = {
  typeName: TYPE_NAME,
  method: "ListPoolInfos",
  Request: QueryListPoolInfosRequest,
  Response: QueryListPoolInfosResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.PoolRewardInfo
 */
export const QueryPoolRewardInfoService = {
  typeName: TYPE_NAME,
  method: "PoolRewardInfo",
  Request: QueryPoolRewardInfoRequest,
  Response: QueryPoolRewardInfoResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.UserRewardInfo
 */
export const QueryUserRewardInfoService = {
  typeName: TYPE_NAME,
  method: "UserRewardInfo",
  Request: QueryUserRewardInfoRequest,
  Response: QueryUserRewardInfoResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.UserPendingReward
 */
export const QueryUserPendingRewardService = {
  typeName: TYPE_NAME,
  method: "UserPendingReward",
  Request: QueryUserPendingRewardRequest,
  Response: QueryUserPendingRewardResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.StableStakeApr
 */
export const QueryStableStakeAprService = {
  typeName: TYPE_NAME,
  method: "StableStakeApr",
  Request: QueryStableStakeAprRequest,
  Response: QueryStableStakeAprResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.PoolAprs
 */
export const QueryPoolAprsService = {
  typeName: TYPE_NAME,
  method: "PoolAprs",
  Request: QueryPoolAprsRequest,
  Response: QueryPoolAprsResponse,
} as const;

/**
 * Queries a list of ShowFeeInfo items.
 *
 * @generated from rpc elys.masterchef.Query.ShowFeeInfo
 */
export const QueryShowFeeInfoService = {
  typeName: TYPE_NAME,
  method: "ShowFeeInfo",
  Request: QueryShowFeeInfoRequest,
  Response: QueryShowFeeInfoResponse,
} as const;

/**
 * Queries a list of ListFeeInfo items.
 *
 * @generated from rpc elys.masterchef.Query.ListFeeInfo
 */
export const QueryListFeeInfoService = {
  typeName: TYPE_NAME,
  method: "ListFeeInfo",
  Request: QueryListFeeInfoRequest,
  Response: QueryListFeeInfoResponse,
} as const;

/**
 * Calculate APR
 *
 * @generated from rpc elys.masterchef.Query.Apr
 */
export const QueryAprService = {
  typeName: TYPE_NAME,
  method: "Apr",
  Request: QueryAprRequest,
  Response: QueryAprResponse,
} as const;

/**
 * Calculate APRs
 *
 * @generated from rpc elys.masterchef.Query.Aprs
 */
export const QueryAprsService = {
  typeName: TYPE_NAME,
  method: "Aprs",
  Request: QueryAprsRequest,
  Response: QueryAprsResponse,
} as const;

/**
 * Queries PoolReward items
 *
 * @generated from rpc elys.masterchef.Query.PoolRewards
 */
export const QueryPoolRewardsService = {
  typeName: TYPE_NAME,
  method: "PoolRewards",
  Request: QueryPoolRewardsRequest,
  Response: QueryPoolRewardsResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.AllLiquidityPoolTVL
 */
export const QueryAllLiquidityPoolTVLService = {
  typeName: TYPE_NAME,
  method: "AllLiquidityPoolTVL",
  Request: QueryAllLiquidityPoolTVLRequest,
  Response: QueryAllLiquidityPoolTVLResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.ChainTVL
 */
export const QueryChainTVLService = {
  typeName: TYPE_NAME,
  method: "ChainTVL",
  Request: QueryChainTVLRequest,
  Response: QueryChainTVLResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.TotalPendingRewards
 */
export const QueryTotalPendingRewardsService = {
  typeName: TYPE_NAME,
  method: "TotalPendingRewards",
  Request: QueryTotalPendingRewardsRequest,
  Response: QueryTotalPendingRewardsResponse,
} as const;

/**
 * @generated from rpc elys.masterchef.Query.PendingRewards
 */
export const QueryPendingRewardsService = {
  typeName: TYPE_NAME,
  method: "PendingRewards",
  Request: QueryPendingRewardsRequest,
  Response: QueryPendingRewardsResponse,
} as const;

