// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file neutron/revenue/tx.proto (package neutron.revenue, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgFundTreasury, MsgFundTreasuryResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "neutron.revenue.Msg";

/**
 * Updates the parameters of the revenue module. This action can only be performed by the
 * module's authority.
 *
 * @generated from rpc neutron.revenue.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

/**
 * FundTreasury funds the revenue treasury module account with the specified amount.
 *
 * @generated from rpc neutron.revenue.Msg.FundTreasury
 */
export const MsgFundTreasuryService = {
  typeName: TYPE_NAME,
  method: "FundTreasury",
  Request: MsgFundTreasury,
  Response: MsgFundTreasuryResponse,
} as const;

