// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file pryzm/amm/v2/pair_match_proposal.proto (package pryzm.amm.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message pryzm.amm.v2.ProposalOrder
 */
export class ProposalOrder extends Message<ProposalOrder> {
  /**
   * should be set to zero for virtual orders
   *
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * this must be provided if and only if virtual=true
   *
   * @generated from field: string max_amount_in = 2;
   */
  maxAmountIn = "";

  /**
   * this must be provided if and only if virtual=true
   *
   * @generated from field: string max_price = 3;
   */
  maxPrice = "";

  /**
   * @generated from field: bool virtual = 4;
   */
  virtual = false;

  constructor(data?: PartialMessage<ProposalOrder>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "pryzm.amm.v2.ProposalOrder";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "max_amount_in", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "max_price", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "virtual", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProposalOrder {
    return new ProposalOrder().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProposalOrder {
    return new ProposalOrder().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProposalOrder {
    return new ProposalOrder().fromJsonString(jsonString, options);
  }

  static equals(a: ProposalOrder | PlainMessage<ProposalOrder> | undefined, b: ProposalOrder | PlainMessage<ProposalOrder> | undefined): boolean {
    return proto3.util.equals(ProposalOrder, a, b);
  }
}

/**
 * @generated from message pryzm.amm.v2.PairMatchProposal
 */
export class PairMatchProposal extends Message<PairMatchProposal> {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId = protoInt64.zero;

  /**
   * @generated from field: bool whitelisted_route = 2;
   */
  whitelistedRoute = false;

  /**
   * @generated from field: string token_in = 3;
   */
  tokenIn = "";

  /**
   * @generated from field: string token_out = 4;
   */
  tokenOut = "";

  /**
   * @generated from field: repeated pryzm.amm.v2.ProposalOrder buy_orders = 5;
   */
  buyOrders: ProposalOrder[] = [];

  /**
   * @generated from field: repeated pryzm.amm.v2.ProposalOrder sell_orders = 6;
   */
  sellOrders: ProposalOrder[] = [];

  constructor(data?: PartialMessage<PairMatchProposal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "pryzm.amm.v2.PairMatchProposal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pool_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "whitelisted_route", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "token_in", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "token_out", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "buy_orders", kind: "message", T: ProposalOrder, repeated: true },
    { no: 6, name: "sell_orders", kind: "message", T: ProposalOrder, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PairMatchProposal {
    return new PairMatchProposal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PairMatchProposal {
    return new PairMatchProposal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PairMatchProposal {
    return new PairMatchProposal().fromJsonString(jsonString, options);
  }

  static equals(a: PairMatchProposal | PlainMessage<PairMatchProposal> | undefined, b: PairMatchProposal | PlainMessage<PairMatchProposal> | undefined): boolean {
    return proto3.util.equals(PairMatchProposal, a, b);
  }
}

