// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file elys/stablestake/tx.proto (package elys.stablestake, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgAddPool, MsgAddPoolResponse, MsgBond, MsgBondResponse, MsgUnbond, MsgUnbondResponse, MsgUpdateParams, MsgUpdateParamsResponse, MsgUpdatePool, MsgUpdatePoolResponse } from "./tx_pb.js";

const TYPE_NAME = "elys.stablestake.Msg";

/**
 * @generated from rpc elys.stablestake.Msg.Bond
 */
export const MsgBondService = {
  typeName: TYPE_NAME,
  method: "Bond",
  Request: MsgBond,
  Response: MsgBondResponse,
} as const;

/**
 * @generated from rpc elys.stablestake.Msg.Unbond
 */
export const MsgUnbondService = {
  typeName: TYPE_NAME,
  method: "Unbond",
  Request: MsgUnbond,
  Response: MsgUnbondResponse,
} as const;

/**
 * @generated from rpc elys.stablestake.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

/**
 * @generated from rpc elys.stablestake.Msg.AddPool
 */
export const MsgAddPoolService = {
  typeName: TYPE_NAME,
  method: "AddPool",
  Request: MsgAddPool,
  Response: MsgAddPoolResponse,
} as const;

/**
 * @generated from rpc elys.stablestake.Msg.UpdatePool
 */
export const MsgUpdatePoolService = {
  typeName: TYPE_NAME,
  method: "UpdatePool",
  Request: MsgUpdatePool,
  Response: MsgUpdatePoolResponse,
} as const;

