// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file elys/perpetual/types.proto (package elys.perpetual, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum elys.perpetual.Position
 */
export enum Position {
  /**
   * @generated from enum value: UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LONG = 1;
   */
  LONG = 1,

  /**
   * @generated from enum value: SHORT = 2;
   */
  SHORT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(Position)
proto3.util.setEnumType(Position, "elys.perpetual.Position", [
  { no: 0, name: "UNSPECIFIED" },
  { no: 1, name: "LONG" },
  { no: 2, name: "SHORT" },
]);

/**
 * @generated from message elys.perpetual.MTP
 */
export class MTP extends Message<MTP> {
  /**
   * @generated from field: string address = 1;
   */
  address = "";

  /**
   * @generated from field: string collateral_asset = 2;
   */
  collateralAsset = "";

  /**
   * @generated from field: string trading_asset = 3;
   */
  tradingAsset = "";

  /**
   * @generated from field: string liabilities_asset = 4;
   */
  liabilitiesAsset = "";

  /**
   * @generated from field: string custody_asset = 5;
   */
  custodyAsset = "";

  /**
   * @generated from field: string collateral = 6;
   */
  collateral = "";

  /**
   * @generated from field: string liabilities = 7;
   */
  liabilities = "";

  /**
   * @generated from field: string borrow_interest_paid_custody = 8;
   */
  borrowInterestPaidCustody = "";

  /**
   * @generated from field: string borrow_interest_unpaid_liability = 10;
   */
  borrowInterestUnpaidLiability = "";

  /**
   * @generated from field: string custody = 11;
   */
  custody = "";

  /**
   * @generated from field: string take_profit_liabilities = 12;
   */
  takeProfitLiabilities = "";

  /**
   * @generated from field: string take_profit_custody = 13;
   */
  takeProfitCustody = "";

  /**
   * @generated from field: string mtp_health = 14;
   */
  mtpHealth = "";

  /**
   * @generated from field: elys.perpetual.Position position = 15;
   */
  position = Position.UNSPECIFIED;

  /**
   * @generated from field: uint64 id = 16;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: uint64 amm_pool_id = 17;
   */
  ammPoolId = protoInt64.zero;

  /**
   * @generated from field: string take_profit_price = 18;
   */
  takeProfitPrice = "";

  /**
   * @generated from field: string take_profit_borrow_factor = 19;
   */
  takeProfitBorrowFactor = "";

  /**
   * @generated from field: string funding_fee_paid_custody = 20;
   */
  fundingFeePaidCustody = "";

  /**
   * @generated from field: string funding_fee_received_custody = 21;
   */
  fundingFeeReceivedCustody = "";

  /**
   * @generated from field: string open_price = 22;
   */
  openPrice = "";

  /**
   * @generated from field: string stop_loss_price = 23;
   */
  stopLossPrice = "";

  /**
   * @generated from field: uint64 last_interest_calc_time = 24;
   */
  lastInterestCalcTime = protoInt64.zero;

  /**
   * @generated from field: uint64 last_interest_calc_block = 25;
   */
  lastInterestCalcBlock = protoInt64.zero;

  /**
   * @generated from field: uint64 last_funding_calc_time = 26;
   */
  lastFundingCalcTime = protoInt64.zero;

  /**
   * @generated from field: uint64 last_funding_calc_block = 27;
   */
  lastFundingCalcBlock = protoInt64.zero;

  constructor(data?: PartialMessage<MTP>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "elys.perpetual.MTP";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "collateral_asset", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "trading_asset", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "liabilities_asset", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "custody_asset", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "collateral", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "liabilities", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "borrow_interest_paid_custody", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "borrow_interest_unpaid_liability", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "custody", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "take_profit_liabilities", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "take_profit_custody", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "mtp_health", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "position", kind: "enum", T: proto3.getEnumType(Position) },
    { no: 16, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 17, name: "amm_pool_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 18, name: "take_profit_price", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 19, name: "take_profit_borrow_factor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 20, name: "funding_fee_paid_custody", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 21, name: "funding_fee_received_custody", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 22, name: "open_price", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 23, name: "stop_loss_price", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 24, name: "last_interest_calc_time", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 25, name: "last_interest_calc_block", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 26, name: "last_funding_calc_time", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 27, name: "last_funding_calc_block", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MTP {
    return new MTP().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MTP {
    return new MTP().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MTP {
    return new MTP().fromJsonString(jsonString, options);
  }

  static equals(a: MTP | PlainMessage<MTP> | undefined, b: MTP | PlainMessage<MTP> | undefined): boolean {
    return proto3.util.equals(MTP, a, b);
  }
}

/**
 * @generated from message elys.perpetual.InterestBlock
 */
export class InterestBlock extends Message<InterestBlock> {
  /**
   * @generated from field: string interest_rate = 1;
   */
  interestRate = "";

  /**
   * @generated from field: int64 block_height = 2;
   */
  blockHeight = protoInt64.zero;

  /**
   * @generated from field: int64 block_time = 3;
   */
  blockTime = protoInt64.zero;

  constructor(data?: PartialMessage<InterestBlock>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "elys.perpetual.InterestBlock";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "interest_rate", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "block_height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "block_time", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InterestBlock {
    return new InterestBlock().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InterestBlock {
    return new InterestBlock().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InterestBlock {
    return new InterestBlock().fromJsonString(jsonString, options);
  }

  static equals(a: InterestBlock | PlainMessage<InterestBlock> | undefined, b: InterestBlock | PlainMessage<InterestBlock> | undefined): boolean {
    return proto3.util.equals(InterestBlock, a, b);
  }
}

/**
 * @generated from message elys.perpetual.FundingRateBlock
 */
export class FundingRateBlock extends Message<FundingRateBlock> {
  /**
   * @generated from field: string funding_rate_long = 1;
   */
  fundingRateLong = "";

  /**
   * @generated from field: string funding_rate_short = 2;
   */
  fundingRateShort = "";

  /**
   * @generated from field: string funding_share_short = 3;
   */
  fundingShareShort = "";

  /**
   * @generated from field: string funding_share_long = 4;
   */
  fundingShareLong = "";

  /**
   * @generated from field: int64 block_height = 5;
   */
  blockHeight = protoInt64.zero;

  /**
   * @generated from field: int64 block_time = 6;
   */
  blockTime = protoInt64.zero;

  constructor(data?: PartialMessage<FundingRateBlock>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "elys.perpetual.FundingRateBlock";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "funding_rate_long", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "funding_rate_short", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "funding_share_short", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "funding_share_long", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "block_height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "block_time", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FundingRateBlock {
    return new FundingRateBlock().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FundingRateBlock {
    return new FundingRateBlock().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FundingRateBlock {
    return new FundingRateBlock().fromJsonString(jsonString, options);
  }

  static equals(a: FundingRateBlock | PlainMessage<FundingRateBlock> | undefined, b: FundingRateBlock | PlainMessage<FundingRateBlock> | undefined): boolean {
    return proto3.util.equals(FundingRateBlock, a, b);
  }
}

/**
 * @generated from message elys.perpetual.WhiteList
 */
export class WhiteList extends Message<WhiteList> {
  /**
   * @generated from field: repeated string validator_list = 1;
   */
  validatorList: string[] = [];

  constructor(data?: PartialMessage<WhiteList>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "elys.perpetual.WhiteList";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "validator_list", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WhiteList {
    return new WhiteList().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WhiteList {
    return new WhiteList().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WhiteList {
    return new WhiteList().fromJsonString(jsonString, options);
  }

  static equals(a: WhiteList | PlainMessage<WhiteList> | undefined, b: WhiteList | PlainMessage<WhiteList> | undefined): boolean {
    return proto3.util.equals(WhiteList, a, b);
  }
}

/**
 * @generated from message elys.perpetual.PositionRequest
 */
export class PositionRequest extends Message<PositionRequest> {
  /**
   * @generated from field: string address = 1;
   */
  address = "";

  /**
   * @generated from field: uint64 id = 2;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<PositionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "elys.perpetual.PositionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PositionRequest {
    return new PositionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PositionRequest {
    return new PositionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PositionRequest {
    return new PositionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PositionRequest | PlainMessage<PositionRequest> | undefined, b: PositionRequest | PlainMessage<PositionRequest> | undefined): boolean {
    return proto3.util.equals(PositionRequest, a, b);
  }
}

