// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file milkyway/rewards/v1/messages.proto (package milkyway.rewards.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgCreateRewardsPlan, MsgCreateRewardsPlanResponse, MsgEditRewardsPlan, MsgEditRewardsPlanResponse, MsgSetWithdrawAddress, MsgSetWithdrawAddressResponse, MsgUpdateParams, MsgUpdateParamsResponse, MsgWithdrawDelegatorReward, MsgWithdrawDelegatorRewardResponse, MsgWithdrawOperatorCommission, MsgWithdrawOperatorCommissionResponse } from "./messages_pb.js";

const TYPE_NAME = "milkyway.rewards.v1.Msg";

/**
 * CreateRewardsPlan defines the operation for creating a new
 * rewards plan.
 *
 * @generated from rpc milkyway.rewards.v1.Msg.CreateRewardsPlan
 */
export const MsgCreateRewardsPlanService = {
  typeName: TYPE_NAME,
  method: "CreateRewardsPlan",
  Request: MsgCreateRewardsPlan,
  Response: MsgCreateRewardsPlanResponse,
} as const;

/**
 * EditRewardsPlan defines the operation to edit an existing
 * rewards plan.
 *
 * @generated from rpc milkyway.rewards.v1.Msg.EditRewardsPlan
 */
export const MsgEditRewardsPlanService = {
  typeName: TYPE_NAME,
  method: "EditRewardsPlan",
  Request: MsgEditRewardsPlan,
  Response: MsgEditRewardsPlanResponse,
} as const;

/**
 * SetWithdrawAddress defines a method to change the withdraw address
 * for a delegator(or an operator, when withdrawing commission).
 *
 * @generated from rpc milkyway.rewards.v1.Msg.SetWithdrawAddress
 */
export const MsgSetWithdrawAddressService = {
  typeName: TYPE_NAME,
  method: "SetWithdrawAddress",
  Request: MsgSetWithdrawAddress,
  Response: MsgSetWithdrawAddressResponse,
} as const;

/**
 * WithdrawDelegatorReward defines a method to withdraw rewards of delegator
 * from a single delegation target.
 *
 * @generated from rpc milkyway.rewards.v1.Msg.WithdrawDelegatorReward
 */
export const MsgWithdrawDelegatorRewardService = {
  typeName: TYPE_NAME,
  method: "WithdrawDelegatorReward",
  Request: MsgWithdrawDelegatorReward,
  Response: MsgWithdrawDelegatorRewardResponse,
} as const;

/**
 * WithdrawOperatorCommission defines a method to withdraw the
 * full commission to the operator.
 *
 * @generated from rpc milkyway.rewards.v1.Msg.WithdrawOperatorCommission
 */
export const MsgWithdrawOperatorCommissionService = {
  typeName: TYPE_NAME,
  method: "WithdrawOperatorCommission",
  Request: MsgWithdrawOperatorCommission,
  Response: MsgWithdrawOperatorCommissionResponse,
} as const;

/**
 * UpdateParams defines a (governance) operation for updating the module
 * parameters.
 * The authority defaults to the x/gov module account.
 *
 * @generated from rpc milkyway.rewards.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

