// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file coreum/customparams/v1/tx.proto (package coreum.customparams.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EmptyResponse, MsgUpdateStakingParams } from "./tx_pb.js";

const TYPE_NAME = "coreum.customparams.v1.Msg";

/**
 * UpdateStakingParams is a governance operation that sets the staking parameter.
 * NOTE: all parameters must be provided.
 *
 * @generated from rpc coreum.customparams.v1.Msg.UpdateStakingParams
 */
export const MsgUpdateStakingParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateStakingParams",
  Request: MsgUpdateStakingParams,
  Response: EmptyResponse,
} as const;

