// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file noble/dollar/vaults/v1/tx.proto (package noble.dollar.vaults.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgLock, MsgLockResponse, MsgSetPausedState, MsgSetPausedStateResponse, MsgUnlock, MsgUnlockResponse } from "./tx_pb.js";

const TYPE_NAME = "noble.dollar.vaults.v1.Msg";

/**
 * @generated from rpc noble.dollar.vaults.v1.Msg.Lock
 */
export const MsgLockService = {
  typeName: TYPE_NAME,
  method: "Lock",
  Request: MsgLock,
  Response: MsgLockResponse,
} as const;

/**
 * @generated from rpc noble.dollar.vaults.v1.Msg.Unlock
 */
export const MsgUnlockService = {
  typeName: TYPE_NAME,
  method: "Unlock",
  Request: MsgUnlock,
  Response: MsgUnlockResponse,
} as const;

/**
 * @generated from rpc noble.dollar.vaults.v1.Msg.SetPausedState
 */
export const MsgSetPausedStateService = {
  typeName: TYPE_NAME,
  method: "SetPausedState",
  Request: MsgSetPausedState,
  Response: MsgSetPausedStateResponse,
} as const;

