// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file atomone/dynamicfee/v1/tx.proto (package atomone.dynamicfee.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "atomone.dynamicfee.v1.Msg";

/**
 * UpdateParams defines a method for updating the dynamicfee module parameters.
 *
 * @generated from rpc atomone.dynamicfee.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

