// Copyright (c) 2023-2024 Nibi, Inc.

// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file eth/evm/v1/tx.proto (package eth.evm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgConvertCoinToEvm, MsgConvertCoinToEvmResponse, MsgConvertEvmToCoin, MsgConvertEvmToCoinResponse, MsgCreateFunToken, MsgCreateFunTokenResponse, MsgEthereumTx, MsgEthereumTxResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "eth.evm.v1.Msg";

/**
 * EthereumTx defines a method submitting Ethereum transactions.
 *
 * @generated from rpc eth.evm.v1.Msg.EthereumTx
 */
export const MsgEthereumTxService = {
  typeName: TYPE_NAME,
  method: "EthereumTx",
  Request: MsgEthereumTx,
  Response: MsgEthereumTxResponse,
} as const;

/**
 * UpdateParams defined a governance operation for updating the x/evm module
 * parameters. The authority is hard-coded to the x/gov module account
 *
 * @generated from rpc eth.evm.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

/**
 * CreateFunToken: Create a "FunToken" mapping. Either the ERC20 contract
 * address can be given to create the mapping to a Bank Coin, or the
 * denomination for a Bank Coin can be given to create the mapping to an
 * ERC20.
 *
 * @generated from rpc eth.evm.v1.Msg.CreateFunToken
 */
export const MsgCreateFunTokenService = {
  typeName: TYPE_NAME,
  method: "CreateFunToken",
  Request: MsgCreateFunToken,
  Response: MsgCreateFunTokenResponse,
} as const;

/**
 * ConvertCoinToEvm: Sends a coin with a valid "FunToken" mapping to the
 * given recipient address ("to_eth_addr") in the corresponding ERC20
 * representation.
 *
 * @generated from rpc eth.evm.v1.Msg.ConvertCoinToEvm
 */
export const MsgConvertCoinToEvmService = {
  typeName: TYPE_NAME,
  method: "ConvertCoinToEvm",
  Request: MsgConvertCoinToEvm,
  Response: MsgConvertCoinToEvmResponse,
} as const;

/**
 * ConvertEvmToCoin: Sends an ERC20 token with a valid "FunToken" mapping to the
 * given recipient address as a bank coin.
 *
 * @generated from rpc eth.evm.v1.Msg.ConvertEvmToCoin
 */
export const MsgConvertEvmToCoinService = {
  typeName: TYPE_NAME,
  method: "ConvertEvmToCoin",
  Request: MsgConvertEvmToCoin,
  Response: MsgConvertEvmToCoinResponse,
} as const;

