// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file sunrise/tokenconverter/v1/tx.proto (package sunrise.tokenconverter.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgConvert, MsgConvertResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "sunrise.tokenconverter.v1.Msg";

/**
 * UpdateParams defines a (governance) operation for updating the module
 * parameters. The authority defaults to the x/gov module account.
 *
 * @generated from rpc sunrise.tokenconverter.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

/**
 * Convert
 *
 * @generated from rpc sunrise.tokenconverter.v1.Msg.Convert
 */
export const MsgConvertService = {
  typeName: TYPE_NAME,
  method: "Convert",
  Request: MsgConvert,
  Response: MsgConvertResponse,
} as const;

